export const TranslateVn = {
  email: 'Email',
  month: 'Tháng',
  luong_cung: 'Lương cứng',
  ngay_cong: 'Ngày công',
  luong_tac_vu_TK_BT: 'Lương tác vụ TKBT',
  tong_tac_vu: 'Tổng tác vụ',
  ngay_cong_thuc_te: 'Ngày công thực tế',
  nsld: 'NSLĐ',
  luong_tac_vu_khac: 'Lương tác vụ khác',
  luong_kpis: 'Lương KPIs',
  luong_chat_luong: 'Lương chất lượng',
  luong_san_pham: 'Lương sản phẩm',
  cl7n: 'CL7N',
  do_hai_long_KH: 'Độ hài lòng KH',
  roi_mang: 'KH rời mạng',
  ho_tro_dia_ban: 'Hỗ trợ địa bàn',
  che_tai: 'Chế tài',
  thu_chi_khac: 'Thu chi khác',
  luong_san_pham_khac: 'Lương sản phẩm khác',
  hoa_hong_ban_hang: 'Hoa hồng bán hàng',
  luong_thu_cuoc_khong_chuyen: 'Lương thu cước không chuyên',
  cac_khoan_bo_sung: 'Các khoản bổ sung',
  ty_le_thu_hoi: 'Tỷ lệ thu hồi',
  thuc_thu: 'Thực thu',
  luong_theo_gia_tri_tien_thu: 'Lương theo giá trị tiền thu',
  luong_co_dinh: 'Lương cố định',
  thuong_phat: 'Thưởng/phạt',
  chi_tieu: 'Chỉ tiêu',
  thuong_phat_chi_tieu: 'Thưởng đạt chỉ tiêu',
  thuong_muc_3: 'Thưởng mức 3 (lương thu bill vượt tỷ lệ)',
  phat_khong_dat_chi_tieu: 'Phạt không đạt chỉ tiêu',
  thanh_toan_online: 'Thanh toán online',
  thi_phan_bac: 'Thi phân bậc',
  luong_recare: 'Lương recare',
  recare_tu_thu: 'Recare tự thu',
  recare_thu_ho: 'Recare thu hộ',
  luong_recare_dao_han_ra_cuoc: 'Lương recare đáo hạn ra cước',
  luong_thu_hoi_bill_bi_dong_ngay_20: 'Lương thu hồi bill bị động ngày 20',
  luong_kpdv: 'Lương KPDV',
  thu_lao_thu_hoi_thiet_bi: 'Thù lao thu hồi thiết bị',
  luong_thu_hoi_bill_cnqh: 'Lương thu hồi Bill CNQH',
  luong_theo_chinh_sach: 'Lương theo chính sách',
  luong_bk1_add_bill_tra_truoc_ngoai_cs: 'Lương BK1 ADD bill trả trước ngoài CS',
  kick_off: ' Kick Off',
  cs_thu_hoi_bi_dong_dich_chuyen_httt_v5_t02: 'Cs thu hồi bị động - dịch chuyển HTTT V5 T02',
  ho_tro: 'Hỗ trợ',
  nhan_vien_moi: 'Nhân viên mới',
  nghi_thai_san: 'Nghỉ thai sản',
  nha_tuyen: 'Nhả tuyển/không nhận ca',
  luong_don_tru: 'Lương đồn trú',
  cl_lap: 'KH>=2CL',
  do_hai_long_kh: 'Độ hài lòng KH',
  nhan_vien: 'Nhân viên',
  cldv: 'CLDV',
  thuong_nsld: 'Thưởng NSLĐ cá nhân',
  tong_cl_bao_tri: 'Tổng CL bảo trì',
  nsld_ca_nhan: 'NSLĐ cá nhân',
  thuong_chi_tieu_nhom: 'Thưởng chỉ tiêu nhóm',
  nsld_nhom: 'NSLĐ nhóm',
  tien_gui_xe: 'Tiền gửi xe',
  dao_tao: 'Đào tạo',
  luong_bao_tri: 'Lương bảo trì',
  tong_ca_vu_bao_tri: 'Tổng ca, vụ bảo trì',
  // phat_cl_phat_sinh: 'Phạt CL PS từ lần thứ 2 trở lên',
  luong_thu_viec: 'Lương thử việc',
  luong_theo_au: 'Lương theo AU',
  luong_trien_khai: 'Lương triển khai',
  phu_cap: 'Phụ cấp',
  truc_su_kien: 'Trực sự kiện',
  trach_nhiem: 'Trách nhiệm',
  luong_vhht: 'Lương VHHT',
  luong_ptht: 'Lương PTHT',
  luong_nang_suat: 'Lương năng suất',
  thanh_tich_dac_biet: 'Thành tích đặc biệt',
  container: 'Container',
  swap: 'Swap',
  luong_thang: 'Lương tháng',
  luong_dao_tao_nghe: 'Lương đào tạo nghề',
  luong_cong_thuc: 'Lương công thức',
  luong_dong_bhxh: 'Lương đóng BHXH',
  bhyt: 'BHYT',
  bhxh: 'BHXH',
  bhtn: 'BHTN',
  kinh_phi_cd: 'Kinh phí CD',
  giam_tru_gia_canh: 'Giảm trừ gia cảnh',
  thue_thu_nhap_ca_nhan: 'Thuế TNCN',
  bu_tru_khac_sau_thue: 'Bù trừ khác sau thuế',
  luong_thuc_nhan: 'Lương thực nhận',
  hinh_thuc_chi_tra: 'Hình thức chi trả',
  emp_name: 'Tên nhân viên',
  emp_code: 'Mã nhân viên',
  birthday: 'Ngày sinh',
  job_title: 'Chức vụ',
  child_depart: 'Phòng ban',
  mobile_phone: 'Số điện thoại',
  mstcn: 'Mã số thuế',
  dependent_info: 'Giảm trừ gia cảnh',
  contract_type: 'Loại hợp đồng',
  contract_begin: 'Ngày bắt đầu',
  contract_end: 'Ngày kết thúc',
  account_number: 'Số tài khoản',
  type_salary: 'Loại lương',
  truy_thu_hoan_thue_TNCN: 'Truy thu/hoàn thuế TNCN',
  truy_thu_BHYT: 'Truy thu BHYT',
  tam_ung: 'Tạm ứng',
  hoan_ung: 'Hoàn ứng',
  bu_tru_luong_thang_t_1: 'Bù trừ lương tháng T-1',
  khen_thuong: 'Khen thưởng',
  cac_khoan_ho_tro_khac: 'Các khoản hỗ trợ khác',
  nhom_dao_tao: 'Nhóm đào tạo',
  cap_the_chung_chi: 'Cấp thẻ/chứng chỉ',
  ngay_cap_the_ATLD: 'Ngày cấp thẻ ATLĐ',
  ngay_het_han_ATLD: 'Ngày hết hạn ATLĐ',
  ngay_bat_dau_dao_tao: 'Ngày bắt đầu đào tạo',
  ngay_ket_thuc_dao_tao: 'Ngày kết thúc đào tạo',
  tinh_trang_the_chung_chi: 'Tình trạng thẻ/chứng nhận',
  hinh_anh_the_chung_nhan: 'Hình ảnh thẻ/chứng nhận (bao gồm cả mặt trước + sau)',
  luong_ca_vu_tru_ES: 'Lương ca, vụ (trừ ES)',
  luong_ca_vu_ES: 'Lương ca, vụ ES',
  bao_hanh_chat_luong: 'KH rời mạng',
  sl_nguoi_phu_thuoc: 'SL người phụ thuộc',
  muc_giam_tru_npt: 'Mức giảm trừ NPT',
  bac_dieu_hanh: 'Bậc điều hành',
  luong_quy_mo_nhan_su: 'Lương quy mô nhân sự',
  so_ns_quan_ly: 'Số NS quản lý',
  luong_hieu_qua_nhan_su: 'Lương hiệu quả nhân sự',
  diem_nsld_trung_binh: 'Điểm NSLĐ trung bình',
  thuong_csat: 'Thưởng CSAT',
  thuong_cem: 'Thưởng CEM',
  thuong_ty_le_clps_7n_sau_tkbt: 'Thưởng tỷ lệ CLPS 7 ngày sau TKBT',
  thuong_giu_chan_kh: 'Thưởng giữ chân khách hàng',
  thuong_trien_khai_dung_hen: 'Thưởng triển khai đúng hẹn',
  thuong_bao_tri_dung_hen: 'Thưởng bảo trì đúng hẹn',
  thuong_bao_tri_dut_diem: 'Thưởng bảo trì dứt điểm',
  thu_nhap_khac: 'Thu nhập khác',
  luong_tac_vu: 'Lương tác vụ',
  kpis: 'KPIs',
  clps: 'CLPS',
  do_chinh_xac: 'Độ chính xác',
  luong_tac_vu_bt: 'Lương tác vụ BT',
  ho_tro_kh_thanh_cong: 'Hỗ trợ KH thành công',
  tong_diem_nsld: 'Tổng điểm NSLĐ',
  phu_cap_ngoai_gio_lam_viec: 'Phụ cấp ngoài giờ làm việc',
  luong_goi_cuoc_cao: 'Lương gói cước cao',
  ty_le_clps_block: 'Tỷ lệ CLPS/block',
  thi_dua: 'Thi đua (nếu có)',
  cac_khoan_thu_nhap_khac: 'Các khoản thu nhập khác',
  cac_khoan_phu_cap_khac: 'Các khoản phụ cấp khác',
  phu_cap_di_chuyen: 'Phụ cấp di chuyển',
  ghi_chu_bu_tru_khac: 'Ghi chú bù trừ khác'
};
