// @ts-ignore
// tslint:disable-next-line:max-line-length
const salaryTF = {
  luong_tf_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  luong_san_pham: '',
  luong_tac_vu_TK_BT: '',
  tong_tac_vu: '',
  ngay_cong_thuc_te: '',
  nsld: '',
  luong_tac_vu_khac: '',
  luong_kpis: '',
  luong_chat_luong: '',
  cl7n: '',
  do_hai_long_kh: '',
  roi_mang: '',
  ho_tro_dia_ban: '',
  che_tai: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  luong_san_pham_khac: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: ''
};
const salaryDH = {
  luong_dh_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  luong_san_pham: '',
  ngay_cong_thuc_te: '',
  luong_ca_vu_tru_ES: '',
  luong_ca_vu_ES: '',
  luong_chat_luong: '',
  clps: '',
  cl_lap: '',
  roi_mang: '',
  // bao_hanh_chat_luong: '',
  // do_hai_long_KH: '',
  phu_cap: '',
  che_tai: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  luong_san_pham_khac: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: ''
};
const salaryABCD = {
  luong_nhom_abcd_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  luong_kpis: '',
  thu_chi_khac: '',
  cac_khoan_bo_sung: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: ''
};

const salaryThuCuoc = {
  luong_thu_cuoc_id: '',
  email: '',
  month: '',
  ty_le_thu_hoi: '',
  thuc_thu: '',
  luong_san_pham: '',
  luong_theo_gia_tri_tien_thu: '',
  luong_co_dinh: '',
  thuong_phat: '',
  chi_tieu: '',
  thuong_phat_chi_tieu: '',
  thuong_muc_3: '',
  phat_khong_dat_chi_tieu: '',
  thanh_toan_online: '',
  roi_mang: '',
  thi_phan_bac: '',
  luong_recare: '',
  recare_tu_thu: '',
  recare_thu_ho: '',
  luong_recare_dao_han_ra_cuoc: '',
  luong_thu_hoi_bill_bi_dong_ngay_20: '',
  luong_kpdv: '',
  thu_lao_thu_hoi_thiet_bi: '',
  luong_thu_hoi_bill_cnqh: '',
  luong_theo_chinh_sach: '',
  luong_bk1_add_bill_tra_truoc_ngoai_cs: '',
  kick_off: '',
  cs_thu_hoi_bi_dong_dich_chuyen_httt_v5_t02: '',
  ho_tro: '',
  nhan_vien_moi: '',
  nghi_thai_san: '',
  che_tai: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  luong_san_pham_khac: '',
  hoa_hong_ban_hang: ''
};
const salaryTKBT = {
  luong_tk_bt_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  luong_san_pham: '',
  luong_tac_vu_TK_BT: '',
  tong_tac_vu: '',
  ngay_cong_thuc_te: '',
  nsld: '',
  luong_tac_vu_khac: '',
  luong_kpis: '',
  luong_chat_luong: '',
  cl7n: '',
  nha_tuyen: '',
  roi_mang: '',
  do_hai_long_kh: '',
  che_tai: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  luong_san_pham_khac: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: '',
  luong_don_tru: ''
};

const salaryTNOS = {
  luong_tn_os_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  luong_chat_luong: '',
  nsld: '',
  luong_kpis: '',
  cl_lap: '',
  roi_mang: '',
  do_hai_long_kh: '',
  nhan_vien: '',
  cldv: '',
  che_tai: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  cac_khoan_bo_sung: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: ''
};

const salaryKeyINDO = {
  luong_key_indo_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  luong_san_pham: '',
  thuong_nsld: '',
  tong_cl_bao_tri: '',
  ngay_cong_thuc_te: '',
  nsld_ca_nhan: '',
  thuong_chi_tieu_nhom: '',
  nsld_nhom: '',
  luong_kpis: '',
  cl_lap: '',
  roi_mang: '',
  do_hai_long_kh: '',
  ho_tro: '',
  tien_gui_xe: '',
  dao_tao: '',
  che_tai: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  luong_san_pham_khac: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: '',
};

const salaryINDO = {
  luong_indo_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  luong_san_pham: '',
  luong_bao_tri: '',
  tong_ca_vu_bao_tri: '',
  ngay_cong_thuc_te: '',
  nsld: '',
  phat_cl_phat_sinh: '',
  roi_mang: '',
  do_hai_long_kh: '',
  ho_tro: '',
  tien_gui_xe: '',
  che_tai: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  luong_thu_viec: '',
  luong_san_pham_khac: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: '',
  luong_chat_luong: '',
};

const salaryFTI = {
  luong_fti_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  luong_san_pham: '',
  luong_theo_au: '',
  luong_trien_khai: '',
  tong_tac_vu: '',
  ngay_cong_thuc_te: '',
  luong_tac_vu_khac: '',
  luong_kpis: '',
  phu_cap: '',
  truc_su_kien: '',
  ho_tro_dia_ban: '',
  trach_nhiem: '',
  che_tai: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  luong_san_pham_khac: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: '',
  luong_chat_luong: ''
};

const salaryINF = {
  luong_inf_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  luong_san_pham: '',
  luong_vhht: '',
  luong_ptht: '',
  luong_nang_suat: '',
  thanh_tich_dac_biet: '',
  phu_cap: '',
  container: '',
  swap: '',
  tien_gui_xe: '',
  che_tai: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  luong_san_pham_khac: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: ''
};

const salaryHachToan = {
  luong_hoach_toan_id: '',
  email: '',
  month: '',
  luong_thang: '',
  luong_thu_viec: '',
  luong_dao_tao_nghe: '',
  luong_cong_thuc: '',
  luong_dong_bhxh: '',
  bhyt: '',
  bhxh: '',
  bhtn: '',
  kinh_phi_cd: '',
  giam_tru_gia_canh: '',
  thue_thu_nhap_ca_nhan: '',
  bu_tru_khac_sau_thue: '',
  truy_thu_hoan_thue_TNCN: '',
  truy_thu_BHYT: '',
  tam_ung: '',
  hoan_ung: '',
  luong_thuc_nhan: '',
  hinh_thuc_chi_tra: '',
  sl_nguoi_phu_thuoc: '',
  muc_giam_tru_npt: ''
};
const salaryDHTIN = {
  luong_dh_tin_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  bac_dieu_hanh: '',
  luong_san_pham: '',
  ngay_cong_thuc_te: '',
  luong_quy_mo_nhan_su: '',
  so_ns_quan_ly: '',
  luong_hieu_qua_nhan_su: '',
  diem_nsld_trung_binh: '',
  luong_chat_luong: '',
  thuong_csat: '',
  thuong_cem: '',
  thuong_ty_le_clps_7n_sau_tkbt: '',
  thuong_giu_chan_kh: '',
  thuong_trien_khai_dung_hen: '',
  thuong_bao_tri_dung_hen: '',
  thuong_bao_tri_dut_diem: '',
  phu_cap: '',
  thu_nhap_khac: '',
  che_tai: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  luong_san_pham_khac: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: '',
  ghi_chu_bu_tru_khac: ''
};
const salaryTestTB = {
  luong_test_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  luong_san_pham: '',
  luong_tac_vu: '',
  tong_tac_vu: '',
  ngay_cong_thuc_te: '',
  nsld: '',
  luong_chat_luong: '',
  kpis: '',
  do_chinh_xac: '',
  che_tai: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  luong_san_pham_khac: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: ''
};
const salarySOPNC = {
  luong_so_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  luong_san_pham: '',
  luong_tac_vu_bt: '',
  tong_tac_vu: '',
  ngay_cong_thuc_te: '',
  nsld: '',
  luong_tac_vu_khac: '',
  luong_chat_luong: '',
  kpis: '',
  cl7n: '',
  roi_mang: '',
  do_hai_long_kh: '',
  ho_tro_kh_thanh_cong: '',
  che_tai: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  luong_san_pham_khac: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: ''
};
const salaryTKBTTIN = {
  luong_tkbt_tin_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  luong_san_pham: '',
  luong_nang_suat: '',
  ngay_cong_thuc_te: '',
  tong_diem_nsld: '',
  nsld: '',
  thuong_nsld: '',
  phu_cap_ngoai_gio_lam_viec: '',
  luong_goi_cuoc_cao: '',
  luong_tac_vu_khac: '',
  luong_kpis: '',
  thuong_csat: '',
  thuong_cem: '',
  thuong_trien_khai_dung_hen: '',
  thuong_bao_tri_dung_hen: '',
  luong_chat_luong: '',
  cl7n: '',
  nha_tuyen: '',
  kh_roi_mang: '',
  ty_le_clps_block: '',
  che_tai: '',
  thu_nhap_khac: '',
  thi_dua: '',
  cac_khoan_thu_nhap_khac: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_phu_cap_khac: '',
  luong_san_pham_khac: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: '',
  luong_don_tru: '',
  ghi_chu_bu_tru_khac: ''

};
const salaryTFTIN = {
  luong_tf_tin_id: '',
  email: '',
  month: '',
  luong_cung: '',
  ngay_cong: '',
  luong_san_pham: '',
  luong_tac_vu_TK_BT: '',
  tong_tac_vu: '',
  ngay_cong_thuc_te: '',
  nsld: '',
  thuong_nsld: '',
  phu_cap_ngoai_gio_lam_viec: '',
  luong_goi_cuoc_cao: '',
  luong_tac_vu_khac: '',
  luong_kpis: '',
  thuong_csat: '',
  thuong_cem: '',
  thuong_trien_khai_dung_hen: '',
  thuong_bao_tri_dung_hen: '',
  luong_chat_luong: '',
  cl7n: '',
  nha_tuyen: '',
  kh_roi_mang: '',
  ty_le_clps_block: '',
  phu_cap_di_chuyen: '',
  che_tai: '',
  thu_nhap_khac: '',
  thi_dua: '',
  cac_khoan_thu_nhap_khac: '',
  thu_chi_khac: '',
  bu_tru_luong_thang_t_1: '',
  khen_thuong: '',
  cac_khoan_ho_tro_khac: '',
  luong_san_pham_khac: '',
  hoa_hong_ban_hang: '',
  luong_thu_cuoc_khong_chuyen: '',
  ghi_chu_bu_tru_khac: ''
};

export const salaryType = {salaryTF, salaryABCD, salaryDH, salaryFTI, salaryINDO, salaryKeyINDO,
  salaryINF, salaryThuCuoc, salaryTNOS, salaryTKBT, salaryHachToan, salaryDHTIN, salaryTestTB,
  salarySOPNC, salaryTKBTTIN, salaryTFTIN};
