export const TranslateEnglish = {
    Email: 'email',
    Tháng: 'month',
    'Lương cứng': 'luong_cung',
    'Ngày công': 'ngay_cong',
    'Lương sản phẩm': 'luong_san_pham',
    'Lương chất lượng': 'luong_chat_luong',
    'Lương tác vụ TKBT': 'luong_tac_vu_TK_BT',
    'Tổng tác vụ': 'tong_tac_vu',
    'Ngày công thực tế': 'ngay_cong_thuc_te',
    NSLĐ: 'nsld',
    'Lương tác vụ khác': 'luong_tac_vu_khac',
    'Lương KPIs': 'luong_kpis',
    // 'Lương chất lượng': 'luong_chat_luong',
    CL7N: 'cl7n',
    'Độ hài lòng KH': 'do_hai_long_kh',
    'KH rời mạng': 'roi_mang',
    // 'KH rời mạng': 'bao_hanh_chat_luong',
    'Hỗ trợ địa bàn': 'ho_tro_dia_ban',
    'Chế tài': 'che_tai',
    'Thu chi khác': 'thu_chi_khac',
    'Lương sản phẩm khác': 'luong_san_pham_khac',
    'Hoa hồng bán hàng': 'hoa_hong_ban_hang',
    'Lương thu cước không chuyên': 'luong_thu_cuoc_khong_chuyen',
    'Các khoản bổ sung': 'cac_khoan_bo_sung',
    'Tỷ lệ thu hồi': 'ty_le_thu_hoi',
    'Thực thu': 'thuc_thu',
    'Lương theo giá trị tiền thu': 'luong_theo_gia_tri_tien_thu',
    'Lương cố định': 'luong_co_dinh',
    'Thưởng/phạt': 'thuong_phat',
    'Chỉ tiêu': 'chi_tieu',
    'Thưởng đạt chỉ tiêu': 'thuong_phat_chi_tieu',
    'Thưởng mức 3 (lương thu bill vượt tỷ lệ)': 'thuong_muc_3',
    'Phạt không đạt chỉ tiêu': 'phat_khong_dat_chi_tieu',
    'Thanh toán online': 'thanh_toan_online',
    'Thi phân bậc': 'thi_phan_bac',
    'Lương recare': 'luong_recare',
    'Recare tự thu': 'recare_tu_thu',
    'Recare thu hộ': 'recare_thu_ho',
    'Lương recare đáo hạn ra cước': 'luong_recare_dao_han_ra_cuoc',
    'Lương thu hồi bill bị động ngày 20': 'luong_thu_hoi_bill_bi_dong_ngay_20',
    'Lương KPDV': 'luong_kpdv',
    'Thù lao thu hồi thiết bị': 'thu_lao_thu_hoi_thiet_bi',
    'Lương thu hồi Bill CNQH': 'luong_thu_hoi_bill_cnqh',
    'Lương theo chính sách': 'luong_theo_chinh_sach',
    'Lương BK1 ADD bill trả trước ngoài CS': 'luong_bk1_add_bill_tra_truoc_ngoai_cs',
    'Kick Off': 'kick_off',
    'Cs thu hồi bị động - dịch chuyển HTTT V5 T02': 'cs_thu_hoi_bi_dong_dich_chuyen_httt_v5_t02',
    'Hỗ trợ': 'ho_tro',
    'Nhân viên mới': 'nhan_vien_moi',
    'Nghỉ thai sản': 'nghi_thai_san',
    'Nhả tuyển/không nhận ca': 'nha_tuyen',
    'Lương đồn trú': 'luong_don_tru',
    'KH>=2CL': 'cl_lap',
    'Nhân viên': 'nhan_vien',
    CLDV: 'cldv',
    'Thưởng NSLĐ cá nhân': 'thuong_nsld',
    'Tổng CL bảo trì': 'tong_cl_bao_tri',
    'NSLĐ cá nhân': 'nsld_ca_nhan',
    'Thưởng chỉ tiêu nhóm': 'thuong_chi_tieu_nhom',
    'NSLĐ nhóm': 'nsld_nhom',
    'Tiền gửi xe': 'tien_gui_xe',
    'Đào tạo': 'dao_tao',
    'Lương bảo trì': 'luong_bao_tri',
    'Tổng ca, vụ bảo trì': 'tong_ca_vu_bao_tri',
    // 'Phạt CL PS từ lần thứ 2 trở lên': 'phat_cl_phat_sinh',
    'Lương thử việc': 'luong_thu_viec',
    'Lương theo AU': 'luong_theo_au',
    'Lương triển khai': 'luong_trien_khai',
    'Phụ cấp': 'phu_cap',
    'Trực sự kiện': 'truc_su_kien',
    'Trách nhiệm': 'trach_nhiem',
    'Lương VHHT': 'luong_vhht',
    'Lương PTHT': 'luong_ptht',
    'Lương năng suất': 'luong_nang_suat',
    'Thành tích đặc biệt': 'thanh_tich_dac_biet',
    Container: 'container',
    Swap: 'swap',
    'KH >=2 CL': 'cl_lap',
    ' Kick Off': 'kick_off',
    'Lương tháng': 'luong_thang',
    'Lương đào tạo nghề': 'luong_dao_tao_nghe',
    'Lương công thức': 'luong_cong_thuc',
    'Lương đóng BHXH': 'luong_dong_bhxh',
    BHYT: 'bhyt',
    BHXH: 'bhxh',
    BHTN: 'bhtn',
    'Kinh phí CD': 'kinh_phi_cd',
    'Giảm trừ gia cảnh': 'giam_tru_gia_canh',
    'Thuế TNCN': 'thue_thu_nhap_ca_nhan',
    'Bù trừ khác sau thuế': 'bu_tru_khac_sau_thue',
    'Lương thực nhận': 'luong_thuc_nhan',
    'Hình thức chi trả': 'hinh_thuc_chi_tra',
    'Truy thu/hoàn thuế TNCN': 'truy_thu_hoan_thue_TNCN',
    'Truy thu BHYT': 'truy_thu_BHYT',
    'Tạm ứng': 'tam_ung',
    'Hoàn ứng': 'hoan_ung',
    'Bù trừ lương tháng T-1': 'bu_tru_luong_thang_t_1',
    'Khen thưởng': 'khen_thuong',
    'Các khoản hỗ trợ khác': 'cac_khoan_ho_tro_khac',
    'Nhóm đào tạo': 'nhom_dao_tao',
    'Cấp thẻ/chứng chỉ': 'cap_the_chung_chi',
    'Ngày cấp thẻ ATLĐ': 'ngay_cap_the_ATLD',
    'Ngày hết hạn ATLĐ': 'ngay_het_han_ATLD',
    'Ngày bắt đầu đào tạo': 'ngay_bat_dau_dao_tao',
    'Ngày kết thúc đào tạo': 'ngay_ket_thuc_dao_tao',
    'Tình trạng thẻ/chứng nhận': 'tinh_trang_the_chung_chi',
    'Hình ảnh thẻ/chứng nhận (bao gồm cả mặt trước + sau)': 'hinh_anh_the_chung_nhan',
    'Mã nhân viên': 'emp_code',
    'Lương ca, vụ (trừ ES)': 'luong_ca_vu_tru_ES',
    'Lương ca, vụ ES': 'luong_ca_vu_ES',
    'SL người phụ thuộc': 'sl_nguoi_phu_thuoc',
    'Mức giảm trừ NPT': 'muc_giam_tru_npt',
    'Bậc điều hành': 'bac_dieu_hanh',
    'Lương quy mô nhân sự': 'luong_quy_mo_nhan_su',
    'Số NS quản lý': 'so_ns_quan_ly',
    'Lương hiệu quả nhân sự': 'luong_hieu_qua_nhan_su',
    'Điểm NSLĐ trung bình': 'diem_nsld_trung_binh',
    'Thưởng CSAT': 'thuong_csat',
    'Thưởng CEM': 'thuong_cem',
    'Thưởng tỷ lệ CLPS 7 ngày sau TKBT': 'thuong_ty_le_clps_7n_sau_tkbt',
    'Thưởng giữ chân khách hàng': 'thuong_giu_chan_kh',
    'Thưởng triển khai đúng hẹn': 'thuong_trien_khai_dung_hen',
    'Thưởng bảo trì đúng hẹn': 'thuong_bao_tri_dung_hen',
    'Thưởng bảo trì dứt điểm': 'thuong_bao_tri_dut_diem',
    'Thu nhập khác': 'thu_nhap_khac',
    'Lương tác vụ': 'luong_tac_vu',
    KPIs: 'kpis',
    CLPS: 'clps',
    'Độ chính xác': 'do_chinh_xac',
    'Lương tác vụ BT': 'luong_tac_vu_bt',
    'Hỗ trợ KH thành công': 'ho_tro_kh_thanh_cong',
    'Tổng điểm NSLĐ': 'tong_diem_nsld',
    'Phụ cấp ngoài giờ làm việc': 'phu_cap_ngoai_gio_lam_viec',
    'Lương gói cước cao': 'luong_goi_cuoc_cao',
    'Tỷ lệ CLPS/block': 'ty_le_clps_block',
    'Thi đua (nếu có)': 'thi_dua',
    'Các khoản thu nhập khác': 'cac_khoan_thu_nhap_khac',
    'Các khoản phụ cấp khác': 'cac_khoan_phu_cap_khac',
    'Phụ cấp di chuyển': 'phu_cap_di_chuyen',

};

